import { TravelCard } from '@/types'

export const mockCards: TravelCard[] = [
  {
    id: '1',
    title: 'Sunrise Hike to Masada',
    description: 'Join us for an epic sunrise hike to the ancient fortress of Masada. We\'ll start at 3:30am to catch the most breathtaking sunrise over the Dead Sea. Bring water, snacks, and good energy!',
    type: 'trip', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Masada National Park', city: 'Dead Sea', country: 'Israel', lat: 31.3156, lng: 35.3534 },
    images: [
      'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    ],
    minParticipants: 8,
    maxParticipants: 20,
    currentParticipants: 5,
    participants: [
      { id: 'p1', user_id: 'mock-1', name: 'Yael Cohen', avatar: 'https://i.pravatar.cc/150?img=1', joinedAt: '2024-03-01' },
      { id: 'p2', user_id: 'mock-2', name: 'Omer Levi', avatar: 'https://i.pravatar.cc/150?img=2', joinedAt: '2024-03-01' },
      { id: 'p3', user_id: 'mock-3', name: 'Sarah Miller', avatar: 'https://i.pravatar.cc/150?img=3', joinedAt: '2024-03-02' },
      { id: 'p4', user_id: 'mock-4', name: 'David Chen', avatar: 'https://i.pravatar.cc/150?img=4', joinedAt: '2024-03-02' },
      { id: 'p5', user_id: 'mock-5', name: 'Emma Wilson', avatar: 'https://i.pravatar.cc/150?img=5', joinedAt: '2024-03-03' },
    ],
    whatsappLink: 'https://chat.whatsapp.com/example1',
    contactInfo: 'yael@example.com',
    createdBy: 'Yael Cohen',
    createdAt: '2024-03-01',
    expiresAt: '2024-04-15',
    tags: ['hiking', 'sunrise', 'history'],
  },
  {
    id: '2',
    title: 'Flamenco Dance Workshop — Barcelona',
    description: 'Authentic flamenco workshop with professional instructor Carmen Rodriguez. Suitable for all levels! We\'ve secured a studio in the Gothic Quarter and need a minimum group to keep costs reasonable.',
    type: 'workshop', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Gothic Quarter Studio', city: 'Barcelona', country: 'Spain', lat: 41.3828, lng: 2.1769 },
    images: [
      'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800',
      'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800',
    ],
    minParticipants: 10,
    maxParticipants: 15,
    currentParticipants: 7,
    participants: [
      { id: 'p6', user_id: 'mock-6', name: 'Maria Garcia', avatar: 'https://i.pravatar.cc/150?img=6', joinedAt: '2024-03-01' },
      { id: 'p7', user_id: 'mock-7', name: 'Tom Brown', avatar: 'https://i.pravatar.cc/150?img=7', joinedAt: '2024-03-02' },
      { id: 'p8', user_id: 'mock-8', name: 'Aisha Patel', avatar: 'https://i.pravatar.cc/150?img=8', joinedAt: '2024-03-02' },
      { id: 'p9', user_id: 'mock-9', name: 'Lucas Silva', avatar: 'https://i.pravatar.cc/150?img=9', joinedAt: '2024-03-03' },
      { id: 'p10', user_id: 'mock-10', name: 'Nina Schmidt', avatar: 'https://i.pravatar.cc/150?img=10', joinedAt: '2024-03-03' },
      { id: 'p11', user_id: 'mock-11', name: 'Alex Kim', avatar: 'https://i.pravatar.cc/150?img=11', joinedAt: '2024-03-04' },
      { id: 'p12', user_id: 'mock-12', name: 'Priya Sharma', avatar: 'https://i.pravatar.cc/150?img=12', joinedAt: '2024-03-04' },
    ],
    telegramLink: 'https://t.me/example2',
    contactInfo: 'maria@example.com',
    createdBy: 'Maria Garcia',
    createdAt: '2024-03-01',
    expiresAt: '2024-04-20',
    tags: ['dance', 'culture', 'workshop'],
  },
  {
    id: '3',
    title: 'Bali Rice Terrace Cycling Tour',
    description: 'Cycling through the stunning Tegallalang rice terraces at sunrise. We\'ll bike through small villages, stop at a local warung for breakfast, and finish with a dip in a hidden waterfall.',
    type: 'trip', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Tegallalang Rice Terraces', city: 'Ubud', country: 'Indonesia', lat: -8.4095, lng: 115.2760 },
    images: [
      'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800',
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800',
    ],
    minParticipants: 6,
    maxParticipants: 12,
    currentParticipants: 4,
    participants: [
      { id: 'p13', user_id: 'mock-13', name: 'Jake Thompson', avatar: 'https://i.pravatar.cc/150?img=13', joinedAt: '2024-03-01' },
      { id: 'p14', user_id: 'mock-14', name: 'Mei Lin', avatar: 'https://i.pravatar.cc/150?img=14', joinedAt: '2024-03-02' },
      { id: 'p15', user_id: 'mock-15', name: 'Carlos Mendez', avatar: 'https://i.pravatar.cc/150?img=15', joinedAt: '2024-03-03' },
      { id: 'p16', user_id: 'mock-16', name: 'Sophie Laurent', avatar: 'https://i.pravatar.cc/150?img=16', joinedAt: '2024-03-04' },
    ],
    whatsappLink: 'https://chat.whatsapp.com/example3',
    contactInfo: 'jake@example.com',
    createdBy: 'Jake Thompson',
    createdAt: '2024-03-02',
    expiresAt: '2024-04-10',
    tags: ['cycling', 'nature', 'culture'],
  },
  {
    id: '4',
    title: 'Tokyo Street Food Night Tour',
    description: 'Explore the hidden izakayas and street food stalls of Shinjuku and Shibuya at night. A local guide will take us off the beaten path to taste authentic ramen, yakitori, and sake.',
    type: 'food', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Shinjuku Station East Exit', city: 'Tokyo', country: 'Japan', lat: 35.6896, lng: 139.7006 },
    images: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
      'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800',
    ],
    minParticipants: 4,
    maxParticipants: 10,
    currentParticipants: 9,
    participants: [
      { id: 'p17', user_id: 'mock-17', name: 'Hiro Tanaka', avatar: 'https://i.pravatar.cc/150?img=17', joinedAt: '2024-03-01' },
      { id: 'p18', user_id: 'mock-18', name: 'Anna Kowalski', avatar: 'https://i.pravatar.cc/150?img=18', joinedAt: '2024-03-01' },
      { id: 'p19', user_id: 'mock-19', name: 'Ben Foster', avatar: 'https://i.pravatar.cc/150?img=19', joinedAt: '2024-03-02' },
      { id: 'p20', user_id: 'mock-20', name: 'Zara Ahmed', avatar: 'https://i.pravatar.cc/150?img=20', joinedAt: '2024-03-02' },
      { id: 'p21', user_id: 'mock-21', name: 'Max Weber', avatar: 'https://i.pravatar.cc/150?img=21', joinedAt: '2024-03-03' },
      { id: 'p22', user_id: 'mock-22', name: 'Yuki Sato', avatar: 'https://i.pravatar.cc/150?img=22', joinedAt: '2024-03-03' },
      { id: 'p23', user_id: 'mock-23', name: 'Lena Fischer', avatar: 'https://i.pravatar.cc/150?img=23', joinedAt: '2024-03-04' },
      { id: 'p24', user_id: 'mock-24', name: 'Omar Hassan', avatar: 'https://i.pravatar.cc/150?img=24', joinedAt: '2024-03-04' },
      { id: 'p25', user_id: 'mock-25', name: 'Rin Watanabe', avatar: 'https://i.pravatar.cc/150?img=25', joinedAt: '2024-03-05' },
    ],
    telegramLink: 'https://t.me/example4',
    contactInfo: 'hiro@example.com',
    createdBy: 'Hiro Tanaka',
    createdAt: '2024-03-01',
    expiresAt: '2024-04-05',
    tags: ['food', 'nightlife', 'culture'],
  },
  {
    id: '5',
    title: 'Surf Lessons — Bondi Beach',
    description: 'Professional surf instructor for beginners and intermediate surfers. Board rental included. We\'ll surf for 2 hours then BBQ on the beach. Need 6 more to make the group discount work!',
    type: 'sport', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Bondi Beach', city: 'Sydney', country: 'Australia', lat: -33.8915, lng: 151.2767 },
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800',
    ],
    minParticipants: 8,
    maxParticipants: 16,
    currentParticipants: 3,
    participants: [
      { id: 'p26', user_id: 'mock-26', name: 'Olivia Brown', avatar: 'https://i.pravatar.cc/150?img=26', joinedAt: '2024-03-01' },
      { id: 'p27', user_id: 'mock-27', name: 'Noah Davis', avatar: 'https://i.pravatar.cc/150?img=27', joinedAt: '2024-03-02' },
      { id: 'p28', user_id: 'mock-28', name: 'Mia Johnson', avatar: 'https://i.pravatar.cc/150?img=28', joinedAt: '2024-03-03' },
    ],
    whatsappLink: 'https://chat.whatsapp.com/example5',
    contactInfo: 'olivia@example.com',
    createdBy: 'Olivia Brown',
    createdAt: '2024-03-02',
    expiresAt: '2024-04-25',
    tags: ['surf', 'beach', 'sport'],
  },
  {
    id: '6',
    title: 'Petra by Night — Jordan',
    description: 'The magical "Petra by Night" experience — the ancient city lit by thousands of candles. We\'re a group of 4 looking for 4-6 more travelers to share transport from Amman and split costs.',
    type: 'attraction', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Petra Archaeological Park', city: 'Petra', country: 'Jordan', lat: 30.3285, lng: 35.4444 },
    images: [
      'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800',
      'https://images.unsplash.com/photo-1563190798-9cf60b08f8bb?w=800',
    ],
    minParticipants: 6,
    maxParticipants: 10,
    currentParticipants: 4,
    participants: [
      { id: 'p29', user_id: 'mock-29', name: 'Amira Khalil', avatar: 'https://i.pravatar.cc/150?img=29', joinedAt: '2024-03-01' },
      { id: 'p30', user_id: 'mock-30', name: 'James Walker', avatar: 'https://i.pravatar.cc/150?img=30', joinedAt: '2024-03-02' },
      { id: 'p31', user_id: 'mock-31', name: 'Fatima Al-Rashid', avatar: 'https://i.pravatar.cc/150?img=31', joinedAt: '2024-03-02' },
      { id: 'p32', user_id: 'mock-32', name: 'Lucas Petit', avatar: 'https://i.pravatar.cc/150?img=32', joinedAt: '2024-03-03' },
    ],
    telegramLink: 'https://t.me/example6',
    contactInfo: 'amira@example.com',
    createdBy: 'Amira Khalil',
    createdAt: '2024-03-01',
    expiresAt: '2024-04-18',
    tags: ['history', 'night', 'UNESCO'],
  },
  {
    id: '7',
    title: 'Northern Lights Hunting — Iceland',
    description: 'Rent a van and head out into the Icelandic wilderness to hunt for the aurora borealis. We have an app that tracks aurora forecasts. Sharing fuel and accommodation costs between travelers.',
    type: 'trip', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Reykjavik', city: 'Reykjavik', country: 'Iceland', lat: 64.1466, lng: -21.9426 },
    images: [
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
      'https://images.unsplash.com/photo-1520769945061-0a448c463865?w=800',
    ],
    minParticipants: 5,
    maxParticipants: 8,
    currentParticipants: 2,
    participants: [
      { id: 'p33', user_id: 'mock-33', name: 'Erik Bjornsson', avatar: 'https://i.pravatar.cc/150?img=33', joinedAt: '2024-03-01' },
      { id: 'p34', user_id: 'mock-34', name: 'Hannah Mueller', avatar: 'https://i.pravatar.cc/150?img=34', joinedAt: '2024-03-02' },
    ],
    whatsappLink: 'https://chat.whatsapp.com/example7',
    contactInfo: 'erik@example.com',
    createdBy: 'Erik Bjornsson',
    createdAt: '2024-03-02',
    expiresAt: '2024-04-30',
    tags: ['aurora', 'nature', 'winter'],
  },
  {
    id: '8',
    title: 'Pottery Workshop — Marrakech Medina',
    description: 'Traditional Moroccan pottery workshop in a riad in the heart of the Medina. Master craftsman Hassan will teach you hand-building and painting techniques. 3-hour workshop, all materials included.',
    type: 'workshop', organizer_role: 'traveler' as const, createdByUserId: 'mock-user',
    location: { address: 'Riad Hassan Studio, Medina', city: 'Marrakech', country: 'Morocco', lat: 31.6295, lng: -7.9811 },
    images: [
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
    ],
    minParticipants: 6,
    maxParticipants: 12,
    currentParticipants: 6,
    participants: [
      { id: 'p35', user_id: 'mock-35', name: 'Layla Hassan', avatar: 'https://i.pravatar.cc/150?img=35', joinedAt: '2024-03-01' },
      { id: 'p36', user_id: 'mock-36', name: 'Pierre Dubois', avatar: 'https://i.pravatar.cc/150?img=36', joinedAt: '2024-03-01' },
      { id: 'p37', user_id: 'mock-37', name: 'Isabella Rossi', avatar: 'https://i.pravatar.cc/150?img=37', joinedAt: '2024-03-02' },
      { id: 'p38', user_id: 'mock-38', name: 'Marco Bianchi', avatar: 'https://i.pravatar.cc/150?img=38', joinedAt: '2024-03-02' },
      { id: 'p39', user_id: 'mock-39', name: 'Chloe Martin', avatar: 'https://i.pravatar.cc/150?img=39', joinedAt: '2024-03-03' },
      { id: 'p40', user_id: 'mock-40', name: 'Rafael Torres', avatar: 'https://i.pravatar.cc/150?img=40', joinedAt: '2024-03-03' },
    ],
    telegramLink: 'https://t.me/example8',
    contactInfo: 'layla@example.com',
    createdBy: 'Layla Hassan',
    createdAt: '2024-03-01',
    expiresAt: '2024-04-12',
    tags: ['craft', 'culture', 'art'],
  },
]
